[tool.poetry]
name = "scidock"
version = "0.1.0"
description = ""
authors = ["kgleba <kgleba@yandex.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
click = "^8.1.7"
requests = "^2.32.3"
crossrefapi = "^1.6.0"
grequests = "^0.7.0"

[tool.poetry.scripts]
scidock = "scidock:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
