version: 1
disable_existing_loggers: false
formatters:
  simple:
    (): colorlog.ColoredFormatter
    format: '%(log_color)s%(levelname)s: %(message)s'
  detailed:
    format: '[%(levelname)s|%(module)s|L%(lineno)d] %(asctime)s: %(message)s'
    datefmt: '%d.%m.%Y %H:%M:%S'
handlers:
  stderr:
    class: logging.StreamHandler
    level: WARNING
    formatter: simple
    stream: ext://sys.stderr
  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: detailed
    filename: ~/.scidock/logs/scidock.log
    maxBytes: 10_000_000
    backupCount: 3
  queue_handler:
    class: logging.handlers.QueueHandler
    handlers:
      - stderr
      - file
    respect_handler_level: true
loggers:
  root:
    level: DEBUG
    handlers:
      - queue_handler