name: Stage
on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install expect
        run: sudo apt install -y expect
      - name: Spin up Docker containers
        run: |
          cd server
          docker compose up -d
      - name: Forward port 8080 to the remote server
        run: expect -c 'spawn ssh -R 8080:0.0.0.0:8080 ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_IP }} ; expect "password:" ; send "${{ secrets.REMOTE_PASSWORD }}\r" ; expect "])?" ; send "y\r" ; interact'