name: Test with PyTest
on:
  push:
    paths:
      - '**.py'
      - '**.yml'
      - '**.yaml'
      - '**.toml'
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python_version: [ '3.10.14', '3.11.9', '3.12.3', '3.13.0-beta.3' ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python_version }}
      - uses: actions/cache@v4
        id: cache-pyproject-deps
        with:
          path: ~/.cache/pip
          key: ubuntu-latest-${{ matrix.python_version }}-pip-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            ubuntu-latest-${{ matrix.python_version }}-pip-
      - name: Install project
        run: pip install .
      - name: Setup the test environment
        run: pip install pexpect pytest
      - name: Run FS pre-init tests
        run: pytest tests/test_fs.py -k init
      - name: Run search tests
        run: pytest tests/test_search.py
      - name: Run FS post-init tests
        run: pytest tests/test_fs.py -k 'not init'