name: Test server with PyTest and Coverage
on:
  push:
    paths:
      - '**.py'
      - '**.yml'
      - '**.yaml'
      - '**.toml'
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Spin up Docker containers
        run: |
          cd server
          docker compose up -d
      - name: Wait until container starts and establishes connections
        run: sleep 5
      - name: Run tests inside the 'web' container
        run: docker exec scidock-server-web-1 ./run_tests.sh
      - name: Extract coverage report from the container
        run: docker cp scidock-server-web-1:/app/coverage.lcov .
      - name: Send coverage reports to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          file: coverage.lcov
      - name: Shut containers gracefully
        run: docker compose down
