name: Test with PyTest
on: [ push, pull_request ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install project
        run: pip install .
      - name: Setup the test environment
        run: pip install pexpect pytest
      - name: Run FS pre-init tests
        run: pytest tests/test_fs.py -k init
      - name: Run search tests
        run: pytest tests/test_search.py
      - name: Run FS post-init tests
        run: pytest tests/test_fs.py -k 'not init'